hack/new-release.sh
/kind bug
/label size/xs
/assign self
/priority critical-urgent
=> Fix repo after org move

Makefile, api/v1alpha1/system_types.go, api/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/saas-operator.clusterserviceversion.yaml, bundle/manifests/saas.3scale.net_systems.yaml, config/crd/bases/saas.3scale.net_systems.yaml, config/manager/kustomization.yaml, config/manifests/bases/saas-operator.clusterserviceversion.yaml, pkg/version/version.go
=> feat: deprecate apicastAccessToken attribute

bundle/manifests/saas-operator.clusterserviceversion.yaml, pkg/version/version.go
Updates the CSV and version.go to 0.10.2.
/kind bug
/assign
=> fix: bump csv version to 0.10.2

controllers/echoapi_controller.go, controllers/echoapi_controller_suite_test.go, controllers/suite_test.go, main.go, pkg/generators/echoapi/deployment.go, pkg/generators/echoapi/generator.go, pkg/generators/echoapi/service.go
Implements the echo-api controller using the new workload reconciler added in #144 
Closes #146 
/assign
/kind feature
=> feat: echo-api controller update to workload reconciler

Makefile, bundle/manifests/saas-operator.clusterserviceversion.yaml, bundle/manifests/saas.3scale.net_autossls.yaml, bundle/manifests/saas.3scale.net_backends.yaml, bundle/manifests/saas.3scale.net_corsproxies.yaml, bundle/manifests/saas.3scale.net_mappingservices.yaml, bundle/manifests/saas.3scale.net_sentinels.yaml, bundle/manifests/saas.3scale.net_systems.yaml, bundle/manifests/saas.3scale.net_twemproxyconfigs.yaml, bundle/manifests/saas.3scale.net_zyncs.yaml, config/crd/bases/saas.3scale.net_twemproxyconfigs.yaml, config/manager/kustomization.yaml, config/manifests/bases/saas-operator.clusterserviceversion.yaml, controllers/mappingservice_controller.go, controllers/mappingservice_controller_suite_test.go, controllers/suite_test.go, main.go, pkg/assets/bindata.go, pkg/generators/mappingservice/config/options.go, pkg/generators/mappingservice/deployment.go, pkg/generators/mappingservice/generator.go, pkg/generators/mappingservice/service.go, pkg/version/version.go
- Implements the **MappingService** controller using the new workload reconciler added in #144.
- Generates alpha release `v0.13.0-alpha.8`
/kind feature
/assign
=> feat: upgrade mapping-service to v2 workload reconciler

controllers/suite_test.go, controllers/zync_controller.go, controllers/zync_controller_suite_test.go, main.go, pkg/generators/zync/api_deployment.go, pkg/generators/zync/config/api_options.go, pkg/generators/zync/config/que_options.go, pkg/generators/zync/generator.go, pkg/generators/zync/que_deployment.go, pkg/generators/zync/services.go
- Implements the **Zync** controller using the new workload reconciler added in #144.
/kind feature
/assign
=> feat: upgrade zync to v2 workload reconciler

controllers/backend_controller_suite_test.go, pkg/generators/backend/generator.go, pkg/generators/backend/listener_deployment.go, pkg/generators/backend/worker_deployment.go, pkg/resource_builders/twemproxy/util.go, pkg/resource_builders/twemproxy/util_test.go
Refactors backend testing with the new helpers.
Adds tests for the backend twemproxy sidecars.
/kind feature
/kind cleanup
/assign
=> feat: Improved backend testing

api/v1alpha1/system_types.go, controllers/system_controller_suite_test.go, pkg/generators/system/app_deployment.go, pkg/generators/system/generator.go, pkg/generators/system/sidekiq_deployment.go, pkg/resource_builders/twemproxy/options.go, pkg/resource_builders/twemproxy/util.go, pkg/resource_builders/twemproxy/util_test.go
Enables the twemproxy sidecar for `system-app` and `system-sidekiq` deployments.
/kind feature
/assign
=> feat: system twemproxy sidecar

controllers/corsproxy_controller_suite_test.go
Updates CORSProxy controller with the new testing toolset
/kind feature
/assign
=> feat: improve corsproxy tests

controllers/echoapi_controller_suite_test.go
Updates EchoAPI controller with the new testing toolset
/kind feature
/assign
=> feat: improve the echo-api tests

controllers/zync_controller_suite_test.go
Updates Zync controller with the new testing toolset, adding more tests to validate resource updates.
/kind feature
/assign
=> feat: Improve Zync tests 

controllers/autossl_controller_suite_test.go, controllers/mappingservice_controller_suite_test.go
Replaces autossl with the new testing toolset
/kind feature
/assign
=> feat: autossl improved testing

controllers/apicast_controller_suite_test.go
Replaces Apicast tests with the new testing toolset, adding canary, update and introspection tests.
/kind feature
/assign
=> feat: improve Apicast tests

Makefile, bundle/manifests/saas-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/api-reference/reference.asciidoc, pkg/version/version.go
0.13.1-alpha.2 release with:
- System canary mechanism
- System twemproxy sidecar
- System console statefulset
- New testing for each controller
/kind feature
/assign
=> release: bump version to alpha.2

Makefile, bundle/manifests/saas-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, go.mod, go.sum, main.go, pkg/util/profiler.go, pkg/version/version.go
Starts a pprof profiler when the `PROFILER_ENABLED` environment variable is true.
Related to the memory leak investigation.
/kind feature
/assign
=> feat: Add profiler

controllers/apicast_controller.go, controllers/autossl_controller.go, controllers/backend_controller.go, controllers/corsproxy_controller.go, controllers/echoapi_controller.go, controllers/mappingservice_controller.go, controllers/redisshard_controller.go, controllers/sentinel_controller.go, controllers/system_controller.go, controllers/twemproxyconfig_controller.go, controllers/zync_controller.go, pkg/reconcilers/basereconciler/v2/reconciler.go, pkg/reconcilers/basereconciler/v2/resources/pdb.go, pkg/reconcilers/basereconciler/v2/resources/services.go, pkg/reconcilers/basereconciler/v2/resources/simple_resources.go, pkg/reconcilers/basereconciler/v2/test/test_controller.go, pkg/reconcilers/workloads/test/test_controller.go
A very simple custom reconciler for PDBs. Also some logging improvements.
/kind feature
/assign
=> pdb custom reconciler

pkg/generators/twemproxyconfig/generator.go
When using the "point to slave RW" feature, this metric reports 1 when
the twemproxyconfig is correctly configured to point to a slaveRW, 0
otherwise (in which case it would be pointing to a master as fallback).
Example:
* In a cluster with no RW slaves, the metric reports 0 for all shards
```bash
❯ curl -s localhost:8080/metrics | grep twemproxyconfig_slave
saas_twemproxyconfig_slave_rw_configured{shard="shard01"} 0
saas_twemproxyconfig_slave_rw_configured{shard="shard02"} 0
```
* If a slave is configured as RW in shard01, the metric changes to 1
```bash
❯ curl -s localhost:8080/metrics | grep twemproxyconfig_slave
saas_twemproxyconfig_slave_rw_configured{shard="shard01"} 1
saas_twemproxyconfig_slave_rw_configured{shard="shard02"} 0
```
/kind feature
/assign …
=> Add metric saas_twemproxy_config_slave_rw_configured

pkg/generators/twemproxyconfig/generator.go
* Adds a label to identify the TwemproxyConfig resource
* FIxes the description
/kind bug
/assign
=> Fix the 'saas_twemproxyconfig_slave_rw_configured' metric

controllers/sentinel_controller.go, pkg/redis/metrics/cluster_status_metrics.go, pkg/redis/metrics/sentinel_metrics.go
Improves the redis info metrics to provide the same information that the Sentinel status provides.
/kind feature
/assign
=> Improve redis server status metrics

Makefile, bundle/manifests/saas-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, pkg/redis/backup/s3upload.go, pkg/ssh/remote_exec.go, pkg/version/version.go
#281 broke the sudo option in backups, this PR fixes it.
/kind bug
/assign
=> Fix sudo in shardedredisbackups

config/local-setup/workloads/mt-ingress.yaml
Small fix for local-setup after the publishing strategies API upgrade.
/kind bug
/assign
=> Fix system-app Service name

pkg/assets/dashboards/redis-sentinel.json.gtpl, pkg/redis/events/watcher.go, pkg/redis/metrics/sentinel_metrics.go, pkg/redis/server/pool.go, pkg/redis/sharded/redis_sharded_cluster.go
/kind feature
/assign
Relates to https://github.com/3scale/platform/issues/1302
=> Add a label with the server alias information for all Sentinel generated metrics

.github/workflows/catalog.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml
=> Add automatic catalog PR opening

Makefile
In line with what was done in https://github.com/3scale-sre/marin3r/pull/283
/kind feature
/assign
=> Update catalog related Makefile targets

docs/release.md
=> Update the release docs
