3scale-sre/saas-operator

roles/backend/templates/backend-grafanadashboard.yaml

On deployed Stg 3scale SaaS Zync Grafana Dashboard, it has been divided pod resources panels by individual deployments, instead of havinf all pods resources from all deployments in the same panel.
`Deployment` variable has an auto discovery template var (so if for example, a part from mandatory `backend-cron`, `backend-listener,` `backend-worker`, you have also deployment `backend-redis` inside the same `Namespace`, it will be added to the backend deployment list).
For each resources panel, there is an auto-repeat per `deployment` var.
Deployment and pod queries has been adjusted to work with this new feature.

Divide backend pod resources dashboard panels by deployments

---

Makefile
deploy/crds/saas.3scale.net_autossls_crd.yaml
deploy/crds/saas.3scale.net_v1alpha1_autossl_cr.yaml
docs/autossl-crd-reference.md
roles/autossl/templates/autossl-service.yaml

AutoSSL needs to have proxy-protocol enabled at AWS ELB, and having proxy protocol enabled make totally unnecessary to have s3 logging configured at AWS ELB.

Remove autossl possibility to configure s3 logging at AWS ELB

---

deploy/clusterrole-aggregations/saas.3scale.net_apicasts.yaml
deploy/clusterrole-aggregations/saas.3scale.net_autossls.yaml
deploy/clusterrole-aggregations/saas.3scale.net_backends.yaml
deploy/clusterrole-aggregations/saas.3scale.net_corsproxies.yaml
deploy/clusterrole-aggregations/saas.3scale.net_echoapis.yaml
deploy/clusterrole-aggregations/saas.3scale.net_mappingservice.yaml
deploy/clusterrole-aggregations/saas.3scale.net_zyncs.yaml

Allows using default `admin`, `view` and `edit` cluster roles for accessing the `saas.3scale.net` resources.

feat: add cluster role aggregations

---

deploy/role.yaml

Using `*` can lead to issues when trying to create a role when the service account is not using a wildcard ruleset:
```
roles.rbac.authorization.k8s.io "threescale-saas-operator" is forbidden: user "system:serviceaccount:default:argocd-manager" (groups=["system:serviceaccounts" "system:serviceaccounts:default" "system:authenticated"]) is attempting to grant RBAC permissions not currently held: 
```

fix: Remove wildcard from saas.3scale.net role rule

---

Makefile
deploy/crds/saas.3scale.net_backends_crd.yaml
docs/backend-crd-reference.md
roles/backend/defaults/main.yml
roles/backend/tasks/main.yml
roles/backend/templates/backend-listener-deployment.yaml
roles/backend/templates/backend-listener-hpa.yaml
roles/backend/templates/backend-listener-internal-service.yaml
roles/backend/templates/backend-listener-pdb.yaml
roles/backend/templates/backend-worker-deployment.yaml
roles/backend/templates/backend-worker-hpa.yaml
roles/backend/templates/backend-worker-pdb.yaml

Closes https://github.com/3scale/saas-operator/issues/8
- Adds Makefile target to run operator locally
- Adds `PodDisruptionBudget` for backend-worker and backend-listener
- Enabled by default (ansible state `present`)
- Configured by default with `maxUnavailable:1`
- CR field can be a `number` or a `percentage` (both cases tested and working)
- If you want to use `minAvailable` instead of default `maxUnavailable`:
- If you add it to the CR from the very beginning, it will be created PDB with `minAvailable` (ignoring default  `maxUnavailable`)
- It PDB was already created with `maxUnavailable`, operator task managing PDB will fail, because ansible operator executed patch operation, and these 2 vars are mutually exclusive and cannot coexists on same PDB
- It happens the same the other way …

Feature/Add HA to backend controller

---

deploy/crds/saas.3scale.net_echoapis_crd.yaml
deploy/crds/saas.3scale.net_v1alpha1_echoapi_cr.yaml
docs/echoapi-crd-reference.md
roles/echoapi/tasks/main.yml
roles/echoapi/templates/echo-api-deployment.yaml
roles/echoapi/templates/echo-api-podmonitor.yaml

Closes https://github.com/3scale/saas-operator/issues/30
- Replaces marin3r deployment annotations managed by  `deploymentAnnotations` map with `marin3r.annotations` map
- Update examples, docs, and added CRD validation for new fields
- Updated PodMonitor interval for envoy-metrics to 60s (it is more than enough, envoy has lots of metrics, and increasing frequency we reduce possibility to fill-up prometheus volume)

Feature/Update marin3r annotations config on EchoAPI controller

---

deploy/role.yaml

On https://github.com/3scale/saas-operator/pull/29 it has been added PDB/HPA management to Backend controller.
I used the operator development mode with my admin credentials and everythign worked as expected while testing new Backend features.
However, when deploying it into staging environment, operator fail to manage PDB and HPA resources because it doesn't have rbac permission.
This PR fixes operator role with required rbac configuration.

Add PDB/HPA rbac permissions to operator role

---

deploy/crds/saas.3scale.net_apicasts_crd.yaml
docs/apicast-crd-reference.md
roles/apicast/defaults/main.yml
roles/apicast/tasks/main.yml
roles/apicast/templates/apicast-deployment.yaml
roles/apicast/templates/apicast-hpa.yaml
roles/apicast/templates/apicast-pdb.yaml

- Update default number of replicas to 2 (like the rest of controllers)
- Add PodDisruptionBudget to apicast deployments
- Add HorizontalPodAutoscaler to apicast deployments
- Add podAntiaffinity to apicast deployments
- Update Apicast CRD with new supported pdb/hpa fields
- Update documentation with new supported pdb/hpa fields

Feature/Add HA to Apicast controller

---

deploy/crds/saas.3scale.net_backends_crd.yaml

Add regex validation to Backend CRD on PDB `minAvailable` and `maxUnavailable` (numbers like `1` and percentages like `80%` are valid)

Add regex validation to Backend CRD PDB fields

---

deploy/crds/saas.3scale.net_zyncs_crd.yaml
docs/zync-crd-reference.md
roles/zync/defaults/main.yml
roles/zync/tasks/main.yml
roles/zync/templates/zync-deployment.yaml
roles/zync/templates/zync-hpa.yaml
roles/zync/templates/zync-pdb.yaml
roles/zync/templates/zync-que-deployment.yaml
roles/zync/templates/zync-que-hpa.yaml
roles/zync/templates/zync-que-pdb.yaml

- Add PodDisruptionBudget to zync deployments
- Add HorizontalPodAutoscaler to zync deployments
- Add podAntiaffinity to zync deployments
- Update Zync CRD with new supported pdb/hpa fields
- Update Zync documentation with new supported pdb/hpa fields

Feature/Add HA to Zync controller

---

deploy/crds/saas.3scale.net_corsproxies_crd.yaml
docs/corsproxy-crd-reference.md
roles/corsproxy/defaults/main.yml
roles/corsproxy/tasks/main.yml
roles/corsproxy/templates/cors-proxy-deployment.yaml
roles/corsproxy/templates/cors-proxy-hpa.yaml
roles/corsproxy/templates/cors-proxy-pdb.yaml

- Add PodDisruptionBudget to cors-proxy deployment
- Add HorizontalPodAutoscaler to cors-proxy deployment
- Add podAntiaffinity to cors-proxy deployment
- Update CORSProxy CRD with new supported pdb/hpa fields
- Update CORSProxy documentation with new supported pdb/hpa fields

Feature/Add HA to CORSProxy controller

---

deploy/crds/saas.3scale.net_mappingservices_crd.yaml
docs/mappingservice-crd-reference.md
roles/mappingservice/defaults/main.yml
roles/mappingservice/tasks/main.yml
roles/mappingservice/templates/mappingservice-deployment.yaml
roles/mappingservice/templates/mappingservice-hpa.yaml
roles/mappingservice/templates/mappingservice-pdb.yaml

- Add PodDisruptionBudget to mapping-service deployment
- Add HorizontalPodAutoscaler to mapping-service deployment
- Add podAntiaffinity to mapping-service deployment
- Update MappingService CRD with new supported pdb/hpa fields
- Update MappingService documentation with new supported pdb/hpa fields

Feature/Add HA to MappingService controller

---

deploy/crds/saas.3scale.net_echoapis_crd.yaml
docs/echoapi-crd-reference.md
roles/echoapi/defaults/main.yml
roles/echoapi/tasks/main.yml
roles/echoapi/templates/echo-api-deployment.yaml
roles/echoapi/templates/echo-api-hpa.yaml
roles/echoapi/templates/echo-api-pdb.yaml

- Add PodDisruptionBudget to echo-api deployment
- Add HorizontalPodAutoscaler to echo-api deployment
- Add podAntiaffinity to echo-api deployment
- Update EchoAPI CRD with new supported pdb/hpa fields
- Update EchoAPI documentation with new supported pdb/hpa fields

Feature/Add HA EchoApi controller

---

roles/system/templates/statefulsets/system-sphinx.yaml

This duplicated valueFrom code block was introduced by the MacBook Pro chaos engineering feature called random double key pressing.

fix: remove duplicated block

---

.circleci/config.yml

A new TAG env var has been added to use semver syntax for bundle targets.

fix: use TAG env var for CircleCI build targets

---

roles/mappingservice/templates/mappingservice-service.yaml

We want to monitor mapping-service  status with blackbox exporter.
Mapping port (the main service port), cannot be used unless we harcode credentials on the probe yaml definition.
So at least by the moment, we are going to monitor the management port, the readiness endpoint `/status/ready`).
This PR publishes the management port in the internal ClusterIp `mapping-service` Service

Add management port to internal mapping-service Service

---

pkg/generators/common_blocks/secrets/secretdefinition.go
pkg/generators/common_blocks/secrets/secretdefinition_test.go

The json decoder needs to be reinitialized for each SeekTo call because the decoder's cursor is moved to the position pointed by the arguments of SeekTo (a jsonpath) and subsequent calls to SeekTo will only find elements that are positioned after the cursor's position.

Fix the secretdefinition generator

---

controllers/apicast_controller.go
controllers/autossl_controller.go
controllers/backend_controller.go
controllers/corsproxy_controller.go
controllers/mappingservice_controller.go
pkg/basereconciler/reconciler.go
pkg/basereconciler/test/test_controller.go

Reconcile was being retried after custom resources were marked for deletion, which is not correct and cause errors to apperar in the logs.

Fix custom resource deletion

---

pkg/generators/backend/listener_deployment.go

When a new backend-listener pod is created, it fails with `CrashLoopBack` error because:
```
/opt/rh/rh-ruby25/root/usr/share/ruby/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): tcp://0.0.0.0: 3000 (URI::InvalidURIError) 
from /opt/rh/rh-ruby25/root/usr/share/ruby/uri/rfc3986_parser.rb:73:in `parse' 
from /opt/rh/rh-ruby25/root/usr/share/ruby/uri/common.rb:237:in `parse' 
...
```
The problem is that it can not bind the desired address because contains a white space between the address and the port: `0.0.0.0: 3000`
This PR just fixes it, as it appears in the official 3scale-operator

Fix backend-listener container args

---

pkg/generators/backend/config/worker_options.go

Fixes a couple of problems in the WorkerOptions definition for backend-worker:
* ConfigInternalAPIUser and ConfigInternalAPIPassword are not relevant for backend-worker
* ConfigWorkerPrometheusMetricsEnabled and ConfigWorkerPrometheusMetricsPort had their envvar names wrong

Fix errors in WorkerOptions

---

api/v1alpha1/backend_types.go

On https://github.com/3scale/apisonator/pull/268 apisonator switched its source image from centos7 with ruby2.5 to ubi8 with ruby 2.7
We have seen on staging that when backend-cron pod is created, has a memory peak of 91MB (then decreases to 42MB), which exceeds default limit of 80MB, so OMM killer kills the pod before running OK.
This PR increases a bit default memory resources to match with current ubi8 usage, so OMM killer won't kill the pod upon startup.

Update default backend-cron memory resources after switch docker base image to ubi8

---

pkg/generators/common_blocks/service/util.go

Right now the echo-api and backend-listener services are created with normal ELBs instead of NLBs, because the `NLBServiceAnnotations` function is not adding the proper annotation needed by aws-controller to create a NLB instead of default ELB.

Fix NLB Service annotations by setting needed aws-load-balancer-type annotation

---

pkg/generators/zync/config/api_options.go
pkg/generators/zync/config/que_options.go

The SecretKeyBase config item had no value assigned.

Add missing SecretKeyBase envvar to Zync deployments

---

Makefile
bundle/manifests/saas-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
pkg/assets/bindata.go
pkg/generators/common_blocks/marin3r/util.go
pkg/generators/common_blocks/marin3r/util_test.go
pkg/version/version.go

Adds the annotation required to all Pods using Envoy sidecars so graceful shutdown of the Envoy server is enabled.
/kind feature
/assign

Enable Envoy sidecars graceful shutdown

---

Makefile
bundle/manifests/saas-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
pkg/generators/system/app_deployment.go
pkg/version/version.go

Adds the `system-app-k8s-deploy` init container that will enqueue some tasks to the sidekiq workers that are required to be scheduled before staring a `system-app` pod.
/kind feature
/assign

feat: add system app init container

---

Makefile
docs/release.md

- Added documentation about release process of stable/alpha releases
- To avoid accidental stable releases creation when you want to do an alpha release, the prepare stable  target has been renamed
- Docs taken from [prometheus-exporter-operator release doc](https://github.com/3scale-ops/prometheus-exporter-operator/blob/main/docs/prometheus-exporter-crd-reference.md), so right now all our 3 operators ([prometheus-exporter-operator](https://github.com/3scale-ops/prometheus-exporter-operator), [marin3r](https://github.com/3scale-ops/marin3r) and [saas-operator](https://github.com/3scale-ops/saas-operator) ) use the exactly same release process (easier maintenance using all of them the same).
/kind documentation
/assign

Add documentation about the operator release process

---

Makefile
api/v1alpha1/system_types.go
api/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/saas-operator.clusterserviceversion.yaml
bundle/manifests/saas.3scale.net_systems.yaml
config/crd/bases/saas.3scale.net_systems.yaml
config/manager/kustomization.yaml
config/manifests/bases/saas-operator.clusterserviceversion.yaml
controllers/system_controller_suite_test.go
pkg/assets/bindata.go
pkg/generators/system/config/options.go
pkg/version/version.go

Replaces system `apicastAccessToken` attribute with `mappingServiceAccessToken` to avoid confusion.
/kind cleanup
/assign
/hold

feat: rename apicast token name

---

Makefile
api/v1alpha1/system_types.go
api/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/saas-operator.clusterserviceversion.yaml
bundle/manifests/saas.3scale.net_systems.yaml
config/crd/bases/saas.3scale.net_systems.yaml
config/manager/kustomization.yaml
config/manifests/bases/saas-operator.clusterserviceversion.yaml
pkg/version/version.go

This adds both `apicastAccessToken` and `mappingServiceAccessToken` as optional, otherwise OLM gets stuck trying to deploy the new version.
/kind feature
/assign

feat: provide a deprecation path for the apicastAccessToken

---

api/v1alpha1/system_types.go
controllers/system_controller_suite_test.go

Related to https://github.com/3scale/deploy/pull/721/files
Adds a new `mailers` queue on the sidekiq low deployment, to send mails on async mode.
/kind feature
/assign

Update system-sidekiq-low deployment to manage new mailers queue

---

config/default/custom/manager_patch.yaml

* Raise memory limit as the operator has a memmory consumption spike
when it starts that can cause crashloopback if the limit is too low
* Raise CPU limit to half a CPU to speed up operator reconcile loops.
Average memory consumption is very low, but we need to allow
consumption spikes to speed up reconcile operations.
/kind bug
/assign

Adjust operator resources

---

controllers/autossl_controller_suite_test.go
pkg/generators/autossl/generator.go

Fixes the empty service selector bug and adds some tests to `autossl` to verify the service selects.
/kind bug
/assign

feat: fix autossl svc selector

---

controllers/corsproxy_controller.go
controllers/corsproxy_controller_suite_test.go
controllers/echoapi_controller.go
controllers/suite_test.go
main.go
pkg/generators/corsproxy/config/options.go
pkg/generators/corsproxy/deployment.go
pkg/generators/corsproxy/generator.go
pkg/generators/corsproxy/service.go
pkg/generators/echoapi/generator.go

Solves part of  https://github.com/3scale-ops/saas-operator/issues/152
- Implements the corsproxy controller using the new workload reconciler added in #144.
- In addition, it updates also the echo-api controller generator by removing error var, because generator function never returns an error https://github.com/3scale-ops/saas-operator/pull/157/commits/34ecee62ac2a899cae48b0caf54009b9a6fd6e08
/kind feature

feat: upgrade cors-proxy to v2 workload reconciler

---

controllers/autossl_controller.go
controllers/backend_controller.go
controllers/corsproxy_controller.go
controllers/echoapi_controller.go
controllers/mappingservice_controller.go
controllers/redisshard_controller.go
controllers/sentinel_controller.go
controllers/zync_controller.go
pkg/reconcilers/basereconciler/v2/reconciler.go
pkg/reconcilers/basereconciler/v2/test/test_controller.go
pkg/reconcilers/workloads/test/test_controller.go

The scheme is already part of the reconciler, so there is no need of
passing it to the function, which is itself a method of the reconciler.
This is probably something that was left from an older implementation.
/kind cleanup
/assign

Do not pass the schema as argument to ReconcileOwnedResources

---

pkg/generators/autossl/deployment.go
pkg/generators/corsproxy/deployment.go
pkg/generators/echoapi/deployment.go
pkg/generators/mappingservice/deployment.go
pkg/generators/zync/api_deployment.go
pkg/generators/zync/que_deployment.go

The name of the containers within the Pod should not be dependant on the name of the component (which changes in the case of canary Deployments for example). This is important as the shutdown manager features in marin3r depend on the name of the containers being always the same. See https://github.com/3scale/3scale-saas/blob/4c71ea98147891dfb147ef4bd4bebe038b1abe1a/manifests/stg-saas/ocp4/3scale-saas/echo-api/stg-saas-echo-api.yaml#L38 as an example of this.
/kind bug
/assign

Hardcode the name of the container for all controllers

---

controllers/suite_test.go

- Adds a container command check.
- When the HPA is enabled, it ignores the Replica number and checks the HPA MinReplica instead.
/kind feature
/assign

feat: Improve workload checks

---

Makefile
README.md
bundle/manifests/saas-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
docs/logging.md
go.mod
main.go
pkg/util/logger.go
pkg/version/version.go

The 3scale SaaS operator uses the [go.uber.org/zap](https://pkg.go.dev/go.uber.org/zap) library for logs.
This PR allows configuring the logger based on environment variables:
| Variable      | Format | Default    | Values                                                 |
| ------------- | ------ | ---------- | ------------------------------------------------------ |
| LOG_MODE      | string | production | `production` / `development`                           |
| LOG_ENCODING  | string | -          | `json` / `console`                                     |
| LOG_LEVEL     | string | -          | `debug`,`info`,`warn`,`error`,`dpanic`,`panic`,`fatal` |
| LOG_VERBOSITY | int8   | 0          | `0-10`                                                 |
Defaults to `production` mode, with the …

feat: env based logger configuration

---

Makefile
bundle.Dockerfile
bundle/manifests/saas-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
config/manager/kustomization.yaml
docs/api-reference/reference.asciidoc
pkg/version/version.go

Release v0.15.0 which includes https://github.com/3scale-ops/saas-operator/pull/202. I have increased the minor release number because it is an important change on how the operator works internally.
I have deployed an alpha release to staging to test that everything runs smoothly.

Release v0.15.0

---

examples/backend/redis.yaml
pkg/redis/metrics/sentinel_metrics.go

When a redis failover occurs, some vectors labelled with an old
combination of redis_server/redis_role keep reportingo old values and
never get updated or deleted.
This PR solves this problem by deleting any stale metrics each time
metrics are gathered from sentinel.
Closes #199 
/kind bug
/assign

Delete stale metrics

---

Makefile
bundle/manifests/saas-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
controllers/twemproxyconfig_controller.go
pkg/version/version.go

Mistakenly, the watch for sentinel events was removed from the TwemproxyConfig controller with commit
8bc3e0d. This is hard to detect because it just makes the reconcile slower so the tests pass. This commit brings back the watch to speed up reconcile times for twemproxy configuration.
/kind bug
/priority critical-urgent
/assign

Fix regression introduced by commit 8bc3e0d

---

controllers/apicast_controller.go
controllers/autossl_controller.go
controllers/backend_controller.go
controllers/backend_controller_suite_test.go
controllers/corsproxy_controller.go
controllers/echoapi_controller.go
controllers/mappingservice_controller.go
controllers/system_controller.go
controllers/system_controller_suite_test.go
controllers/zync_controller.go
pkg/reconcilers/basereconciler/v2/reconciler.go
pkg/reconcilers/basereconciler/v2/resources/hpa.go
pkg/reconcilers/basereconciler/v2/test/test_controller.go
pkg/reconcilers/basereconciler/v2/test/test_controller_suite_test.go
pkg/reconcilers/workloads/resources.go
pkg/reconcilers/workloads/resources_test.go
pkg/reconcilers/workloads/test/test_controller.go
pkg/reconcilers/workloads/test/test_controller_suite_test.go
pkg/resource_builders/hpa/resource.go
test/util/assert.go

- Updates the `autoscaling` to `v2`, as `autoscaling/v2beta2` HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+.
/kind feature
/priority important-longterm 
/assign

fix: Update deprecated autoscaling api

---

controllers/suite_test.go
pkg/reconcilers/basereconciler/v2/test/suite_test.go
pkg/reconcilers/workloads/test/suite_test.go
test/e2e/suite_test.go

GinkgoRandomSeed() is used by ginkgo to randomize certain aspects of a test run and it uses the timestamp. This alone does not fix the issue because the seed is the same for all parallel nodes, so we add to it with the parallel node identifier.
/kind bug
/assign

Fix randomization in parallel ginkgo test runs

---

api/v1alpha1/system_types.go
api/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/saas-operator.clusterserviceversion.yaml
bundle/manifests/saas.3scale.net_apicasts.yaml
bundle/manifests/saas.3scale.net_backends.yaml
bundle/manifests/saas.3scale.net_echoapis.yaml
bundle/manifests/saas.3scale.net_systems.yaml
config/crd/bases/saas.3scale.net_apicasts.yaml
config/crd/bases/saas.3scale.net_backends.yaml
config/crd/bases/saas.3scale.net_echoapis.yaml
config/crd/bases/saas.3scale.net_systems.yaml
config/manifests/bases/saas-operator.clusterserviceversion.yaml
docs/api-reference/reference.asciidoc
pkg/generators/system/config/sphinx_options.go

Following upstream https://github.com/3scale/porta/pull/3162
This PR adds the new sphinx envvar, whose default value for SaaS is `100` (unlike upstream value `1000`, which causes errors in SaaS).
This new field permit us to not have to mount system-config secret on sphinx (containing the sphinx config file), so we can use the sphinx config file from the builtin container, modifying its behavior with this envvar.
/kind feature
/assign

Feat/Add sphinx batch size field to System CR

---

pkg/reconcilers/basereconciler/v2/reconciler.go

Add EnvoyConfig to the list of supported types so the operator automatically prunes them when required
/kind bug
/assign

Prune EnvoyConfigs

---

Makefile
bundle/manifests/saas-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
pkg/assets/bindata.go
pkg/resource_builders/envoyconfig/resource_test.go
pkg/resource_builders/envoyconfig/templates/listeners.go
pkg/resource_builders/envoyconfig/templates/listeners_test.go
pkg/version/version.go

We were taking the remote address from the `X-ENVOY-EXTERNAL-ADDRESS` envoy header, which is not even added when http/1.0 requests are rejected, so the field was empty in the logs. Using the internal variable `DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT` fixes this and remote address is also logged for rejected requests.
/kind bug
/assign

Fix client ip in envoy logs

---

pkg/redis/backup/tag.go

Adds more tags to s3 backup object so the origin server can be identified
/kind feature
/assign

Tag s3 redis backup objects with more info

---

go.mod
go.sum
pkg/generators/system/tekton_pipeline.go
pkg/generators/system/tekton_task.go

/kind bug
/assign
/hold
https://github.com/3scale-ops/basereconciler/pull/5 need to be merged first

Fix tekton reconciliation after upgrade to ocp 4.12

---

go.mod
go.sum

Fixes a bug in the basreconciler. See https://github.com/3scale-ops/basereconciler/pull/6.
/kind bug
/assign

Upgrade to basereconciler v0.3.4

---

controllers/sentinel_controller.go
examples/backend/redis-v6/redis.yaml
examples/backend/redis-v6/sentinel.yaml
go.mod
go.sum
pkg/generators/twemproxyconfig/generator_test.go
pkg/redis/client/fake_client.go
pkg/redis/client/goredis_client.go
pkg/redis/client/interface.go
pkg/redis/server/server.go
pkg/redis/sharded/discover.go
pkg/redis/sharded/redis_shard.go
pkg/redis/sharded/redis_shard_test.go
pkg/redis/sharded/redis_sharded_cluster_test.go

It seems that even though the "sentinel master <shard_name>" command returns updated information about the master as soon as a slave is promoted, there is an exception with the sentinel instance that acts as "failover leader". The failover leader is the instance that actually performs the shard reconfigurations, and in this case, its "sentinel master <shard_name>" command only returns updated information when all the slaves have been also reconfigured to point to the new master. This causes delays in twemproxy reconfiguration if this is the instance used by the twemproxyconfig controller to "discover" the shard.
To detect this situation, add a step that checks the master address with the command "sentinel get-master-addr-by-name <shard_name>". This command always returns updated master …

Avoid failover delays in twemproxy reconfig when using master targets

---

Makefile
bundle/manifests/saas-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
pkg/redis/events/watcher.go
pkg/version/version.go

With recent migrations we saw that failover alert do not work on the first failover upon saas-operator pod creation.
The reason is, there is a timeseries database for every `redis_server`, on latest migrations the failover orcurs on a new redis server instance, passing the counter from `non-exist` to `1`, so prometheus `rate` does not get it.
In the next image, filtering per shard and sentinel, there are 3 timeseriesdb with `0` value (the ones from old redis_servers), and one timeseriesdb with value `1` (new redis_server).
This PR removes the `redis_server` label from **switchMasterCount** metric, the same already done at **failoverAbortNoGoodSlaveCount**, which is the same case, we want a metric per shard only.
/kind bug
/kind release
/assign

Fix/Sentinel switch-master-count metric

---

pkg/generators/system/config/options.go

Align SaaS operator with the changes in porta and 3scale operator:
- 3scale operator: https://github.com/3scale/3scale-operator/pull/821
- porta: https://github.com/3scale/porta/pull/3324
The changes are:
- add a new `BACKEND_URL` environment variable, while still keeping `BACKEND_ROUTE` to ensure smooth transition (to be deleted in future)
- removed `APICAST_BACKEND_ROOT_ENDPOINT` environment variable, it is not in use by `stg-saas` or `pro-saas` environments.

Change env var from BACKEND_ROUTE to BACKEND_URL

---

pkg/assets/dashboards/system.json.gtpl

Two main changes:
- metrics `rails_db_runtime_seconds_sum` and `rails_view_runtime_seconds_sum` have been removed from porta (system) in https://github.com/3scale/porta/pull/3555
- change the graphs to adapt to the changes in the status - now we're not reporting numbers, but aggregated vaues `2xx`, `3xx`, `4xx`, `5xx`, this was implemented in https://github.com/3scale/porta/pull/3648

Update graphs on System dashboard

---

Makefile
bundle/manifests/saas-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
pkg/generators/system/config/options.go
pkg/version/version.go

On https://github.com/3scale/3scale-saas/pull/598 it was added the envvar `BACKEND_URL` which eventually would replace `BACKEND_ROUTE`
Those changes were already deployed in production, as well as the config file change at https://github.com/3scale/3scale-saas/pull/747
So now it is safe to finally remove the deprecated envvar.
/kind cleanup
/assign

Cleanup/Finally remove system deprecated BACKEND_ROUTE envvar

---

config/local-setup/workloads/mt-ingress.yaml

While working on https://github.com/3scale-sre/platform/issues/1598
I saw that mt-ingress did not have monitoring enabled, so I added the required PodMonitor.
/kind feature
/assign

Add prometheus PodMonitor to mt-ingress local-setup
